# codebuild will use this buildspec file to build the docker image and push it to docker hub

version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x # optional : we don't have install python in the container to build the image

  pre_build:
    commands:
      
      - chmod +x build-image.sh push-image.sh # make files executable
      - ./build-image.sh
  build:
    commands:
      - ./push-image.sh